Milkshak3s/CSEC-380-G5

- docs/Activity1_Answers.md
Title is all.
This PR targets issue #1
> Docs: Add skeleton doc for activity 1 answers

- docs/Activity1_Answers.md
Title is good.
This addresses #8
> Docs: Add url of github repo to answers

- docs/Activity1_Answers.md
Title is good.
This addresses #6
> Docs: Answer question about how epics were broken down

- docs/Activity1_Answers.md
Title is good.
This addresses #5
> Docs: Define sprint length

- docs/Activity1_Answers.md
Title is good.
This addresses #7
> Docs: Define how projects are broken up

- docs/Activity1_Answers.md
Title is good.
This addresses #3
> Docs: Define how security will be tested at certain points

- server/frontend/Dockerfile
- server/frontend/index.html
- tests/requirements.txt
- tests/test_helloworld.py
Please review the dummy apache2 frontend (hello world) and the python test file for testing the dummy frontend.
> added dummy frontend and test

- .gitignore
- .travis.yml
> DevOps: Setup travis tests

- docs/Activity1_Answers.md
- docs/Agile_Plan.md
Title is good.
This addresses #4
> Docs: Setup an agile process for project development

- docs/Activity2_Answers.md
Created Activity2 answers
Addressed #12 #13 #14
> Created Activity2 answers

- docker-compose.yml
Title is good.
This addresses #54
> Feature: Add mysql server to docker-compose

- frontend/package.json
- frontend/src/App.js
- frontend/src/components/LoginForm.js
- frontend/src/scenes/AppLogin.js
- frontend/yarn.lock
A frontend landing page, without button functionality. Sends no API requests, but UI elements respond correctly.
This addresses #52
> Feature: Basic login frontend

- backend/app.py
- backend/test.cfg
Provides the API endpoint `/api/v1/token`, which when provided with a valid "token" returns the username of the associated user.
This addresses #50
> Feature: Auth token check

- frontend/src/App.js
Title is good.
This addresses #58
> Feature: Frontend checks token endpoint for token validity

- frontend/src/App.js
- frontend/src/components/LoginForm.js
- frontend/src/components/MainSidebar.js
- frontend/src/components/VideoCard.js
- frontend/src/components/VideoGrid.js
- frontend/src/scenes/AppMain.js
Adds the following frontend components:
- AppMain.js (the app's main scene)
- MainSidebar.js (the sidebar for the app's main scene)
- VideoCard.js (a card representing a single video in list view)
- VideoGrid.js (a flex grid of video cards)
The data is a sample, but otherwise fully ready to integrate with standardized JSON. Log Out button is functional, Upload and Enter URL buttons work button are not linked to a function.
> Feature: Video Display Frontend

- backend/Dockerfile
Title is good.
This addresses #89
> Feature: Setup static hosting folder for backend

- .gitignore
- backend/Dockerfile
- backend/app.cfg
- backend/app.py
- backend/test.cfg
- frontend/src/App.js
- frontend/src/components/LoginForm.js
- frontend/src/components/MainSidebar.js
- frontend/src/components/VideoGrid.js
- frontend/src/scenes/AppMain.js
This PR implements several major changes to the application. They are as follows:
- The list of videos now pulls from the `GET /api/v1/videos` backend endpoint
- The backend endpoint `POST /api/v1/videos` now exists with authentication for uploading new videos
- Added new Video SQLA model
- Frontend main view now displays the proper username
This addresses #73 #74 #88
> Feature: Video Backend & Proper API Requests

- backend/app.py
Title is good.
This addresses #84
> Feature: API Video Link Processing

- backend/app.py
Title is good.
This addresses #81 and #82
> Feature: Backend Endpoints for GET and DELETE video by id

- .gitignore
- backend/Dockerfile
- backend/app.py
- backend/requirements.txt
Change summary:
- sha256 hash stored passwords
- add set_password and check_password methods to User class
- add '-p' flag to mkdir in Dockerfile so it runs w/o error if  directory exists
- tell .gitignore to ignore vim .swp files
> Store passwords hashed in DB (sha256)

- backend/app.py
> Actually fix password auth this time

- tests/test_auth.py
The following code tests cases for #55 #56 #57
> Add authentication test cases

- docs/Activity3_Answers.md
> Add link to test cases

- backend/app.py
- frontend/package.json
- frontend/src/App.js
- frontend/src/components/VideoGrid.js
- frontend/src/components/VideoPlay.js
- frontend/src/scenes/AppPlay.js
- frontend/yarn.lock
Plays a single video from the grid
This addresses #75
> Feature: Play Video

- frontend/src/App.js
- frontend/src/components/VideoCard.js
- frontend/src/components/VideoGrid.js
- frontend/src/scenes/AppPlay.js
Delete buttons work on cards now!
This addresses #95
> Feature: Delete button functionality

- frontend/src/components/LinkModal.js
- frontend/src/components/MainSidebar.js
Got the "add video by URL" working.
This addresses #85
> Feature: Add video links via dialogue

- frontend/src/components/MainSidebar.js
- frontend/src/components/UploadModal.js
We can now upload videos
Addresses #86
> Feature: Upload via modal

- backend/app.py
- frontend/src/components/MainSidebar.js
- frontend/src/components/PingModal.js
Adds a new component for pinging a server (vulnerable to command injection), which alert()s the result
> Add ping UI element for cmd injection

- backend/app.py
- docs/Activity5_Answers.md
- frontend/Dockerfile
- tests/test_cmdinjection.py
- tests/test_sqlinjections.py
This PR resolves issues #108  #104 #103
> Sqli backend2

- backend/app.py
- frontend/src/components/MainSidebar.js
- frontend/src/components/UsersDevModal.js
- frontend/src/components/UsersModal.js
Add a couple of "display users" elements, which show database information on a given user and are vulnerable to SQL injection
> Add frontend SQLi elements

- backend/Dockerfile
- backend/app.py
- docs/Activity6_Answers.md
- tests/test_ssrf.py
This PR addresses and resolves #112 #110 #109 #113 #107
> Finish SSRF backend test and doc

- docs/Activity7_Answers.md
Removed video itself from docs section. Added a line at the beginning of Activity7_Answers containing the link to the video which is shared out from google drive instead
> Command injection stuff

- docs/Activity5_Answers.md
Made videos and put share link to videos in the Activity5_Answers doc
> Sql injection stuff
